/* ==== finder-data.js ==== */
/* data/finder.js -- GENERATED by the exam kit's finder/build_finder.py from finder.json. Do not edit here.
   The problem finder's ladders: families, forms, checks, word list. ASCII only. */
(function (root) {
  root.STEEL_DATA = root.STEEL_DATA || {};
  root.STEEL_DATA.finder = {
 "title": "ARCH-232 problem finder",
 "about": "One data file. finder.py and finder.js follow these ladders mechanically (same rules, tested against each other). build_finder.py turns it into the on-screen finder (PROBLEM-FINDER.html) and the strict instructions for a weak model (WEAK-MODEL-PROMPT.txt). Edit here, then rebuild. ASCII only.",
 "how_to_read": [
  "Type the problem into the box: the whole thing, one lettered part at a time, or just its key words. The page follows this chart for you and shows which words decided it.",
  "To follow it by eye: ignore the cover page (the list of defaults). Find the QUESTION: the sentence that says what to find.",
  "Go down ladder 1. Stop at the FIRST step whose words appear. Capitals do not matter.",
  "Then go down that family's ladder 2, using the QUESTION's words first, to find the exact form.",
  "A problem with parts (a), (b), (c): do this once per part. The set-up at the top tells you the member; the part tells you the form.",
  "If nothing matches, type the strongest word of the problem into the word list."
 ],
 "question_words": [
  "determine",
  "calculate",
  "compute",
  "find ",
  "select",
  "choose",
  "what is",
  "what are",
  "is it",
  "is the",
  "how much",
  "how many",
  "check ",
  "design ",
  "size ",
  "explain",
  "why",
  "define",
  "list ",
  "name ",
  "state ",
  "describe ",
  "?",
  "find:",
  "to find:",
  "required:",
  "determine:",
  "asked:",
  "question:",
  "unknown:",
  "compute:",
  "calculate:",
  "select:",
  "re:^ which |Which ... (first word)",
  "which of",
  "which one",
  "which limit",
  "which axis",
  "which path",
  "which combination",
  "which shape",
  "re:which w ?\\d|which W14 ...",
  "check whether",
  "check if",
  "check the",
  "does the",
  "does it",
  "will the",
  "can the",
  "what size",
  "what shape",
  "express ",
  "convert ",
  "give ",
  "show that",
  "verify",
  "re:^ is |Is ... (first word)",
  "re:^ are |Are ... (first word)",
  "whether"
 ],
 "member_action_words": [
  "select",
  "lightest",
  "choose",
  "most economical",
  "capacity",
  "strength",
  "adequate",
  "size of",
  "phi",
  "moment",
  "reaction",
  "shear",
  "net area",
  "kl/r",
  "zx",
  "re:\\b(mu|vu|ru|ra|rb)\\b|Mu, Vu, RA, RB",
  "check",
  "slenderness",
  "smallest w",
  "smallest shape",
  "smallest section",
  "smallest size",
  "smallest member",
  "smallest column",
  "smallest beam",
  "smallest angle",
  "smallest channel",
  "smallest standard",
  "smallest hss",
  "smallest tee",
  "what size",
  "what shape",
  "strong enough",
  "carry",
  "resist",
  "required area",
  "area is required",
  "euler",
  "does it work",
  "ok",
  "effective length",
  "k factor",
  "buckl",
  "re:\\bkl\\b|KL"
 ],
 "families": [
  {
   "id": "words",
   "use": "question",
   "question": "Does the QUESTION ask for WORDS, not a number? (why, explain, define, is called, what does ... mean, true or false, in one sentence) Or: no numbers anywhere, and nothing to check, size or find?",
   "signals": [
    "which of the following",
    "list the",
    "list two",
    "list three",
    "name the",
    "name two",
    "name three",
    "give two",
    "give three",
    "state the",
    "describe ",
    "limitations",
    "reasons",
    "purpose of",
    "what kind of",
    "what type of"
   ],
   "unless": [
    "calculate",
    "compute",
    "determine",
    "find the",
    "find u",
    "select",
    "lightest",
    "most economical",
    "adequate",
    "how much",
    "re:what (is|are) (the|its|their) (\\w+ ){0,2}(capacity|strength|load|moment|area|reaction|stress|ratio|value|size|pcr|zx)\\b|what is the capacity / load / moment / area ...",
    "effective length factor",
    " k for ",
    " k of ",
    "design k",
    "value of k",
    "factor k",
    "fy and fu",
    "steel grade",
    "what grade",
    "which steel",
    "fy of",
    "fu of",
    "convert",
    "section properties",
    "what size",
    "smallest w",
    "smallest shape",
    "smallest section",
    "smallest size",
    "smallest member",
    "smallest column",
    "smallest beam",
    "smallest angle",
    "smallest channel",
    "smallest standard",
    "smallest hss",
    "smallest tee"
   ],
   "go": "Definitions (top bar)",
   "note": "Type the two or three key words of the question into the search box. It answers in her words, or says it has no entry. If a calculation problem ends with a 'why' or 'explain' part, do that part here separately. NAME / LIST / STATE / DESCRIBE count only when no quantity (strength, capacity, load, moment, area) is being asked for.",
   "strong": [
    "why ",
    "why?",
    "explain",
    "define",
    "definition",
    "is called",
    "are called",
    "what is meant",
    "what does",
    "mean?",
    "true or false",
    "in one sentence",
    "in your own words",
    "in words",
    "no calculation",
    "difference between",
    "advantages",
    "disadvantages",
    "account for",
    "safety factor",
    "leaves out",
    "leave out",
    "briefly"
   ],
   "weak_unless": [
    "capacity",
    "strength",
    "phi",
    "net area",
    "pcr",
    "kips",
    "k/ft",
    "moment",
    "reaction",
    "kl/r",
    " load",
    "area",
    "governs",
    "controls"
   ],
   "no_numbers": true,
   "no_numbers_unless": [
    "check",
    "size",
    "design",
    "select",
    "choose",
    "carry",
    "resist",
    "strong enough",
    "adequate",
    "euler",
    "net area",
    "k factor",
    "factor k",
    "effective length factor",
    "shear lag factor",
    "factor u",
    "kl/r",
    "slenderness",
    "depth of",
    "weight of",
    "propert",
    "deflection",
    "how much",
    "how many",
    "lightest",
    "combination",
    "governs",
    "controls",
    "which k",
    "k applies",
    "what k",
    " k for ",
    "value of k"
   ]
  },
  {
   "id": "convert",
   "use": "question",
   "question": "Does it only ask you to CONVERT a number from one unit to another?",
   "signals": [
    "convert",
    "conversion",
    "express "
   ],
   "unless": [
    "select",
    "lightest",
    "capacity",
    "strength",
    "adequate",
    "moment of",
    "design",
    "size",
    "factored load"
   ],
   "go": "1 Lookup > Units",
   "note": "ft and in, lb/ft and k/ft, psf to k/ft (needs the width), kip-ft and kip-in."
  },
  {
   "id": "lookup",
   "use": "question",
   "question": "Does it only ask for something READ FROM A TABLE, with no loads anywhere? (a property of a named shape, Fy and Fu, the lightest shape with some property, section properties)",
   "signals": [
    "actual depth",
    "actual web",
    "web width",
    "web thickness",
    "flange width",
    "flange thickness",
    "section modulus about",
    "radius of gyration about",
    "moment of inertia about",
    "cross-sectional area of",
    "weight per foot",
    "determine the following",
    "fy and fu",
    "what grade",
    "which steel",
    "fy of",
    "fu of",
    "minimum yield",
    "re:(yield|tensile) (stress|strength) of (a ?\\d|astm|grade|steel)|yield / tensile strength of A36, A992 ...",
    "steel grade",
    "section properties",
    "properties of",
    "with units",
    "re:\\b(a|d|bf|tw|tf|ix|iy|sx|sy|zx|zy|rx|ry|rz|tdes|tnom) of (a|an|the) |rx of a ..., tw of an ...",
    "re:lightest [a-z-]+ ?\\d* with |lightest W.. with (a property)",
    "re:\\b(depth|width|thickness|area|weight) of (a|an|the) ?(w|hss|c|l|wt|s|m|hp|mc|pipe)[ -]?\\d|depth / area / weight of a W18x50",
    "weigh per",
    "fy for",
    "fu for",
    "nominal depth",
    "re:\\b(ix|iy|sx|sy|zx|zy|rx|ry)\\b,? (and|of) |Ix and Sx of ...",
    "re:\\b(ix|iy|sx|sy|zx|zy|rx|ry|bf|tw|tf)\\b (for|of) (a |an |the )?(w|hss|c|l|wt|s|m|hp|mc|pipe)[ -]?\\d|Zx for a W16x40",
    "minimum tensile",
    "specified minimum",
    "strength is specified",
    "section modulus of",
    "plastic section modulus of",
    "moment of inertia of",
    "radius of gyration of"
   ],
   "unless": [
    "kips",
    "k/ft",
    "psf",
    " span",
    "select the lightest",
    "design",
    "lrfd",
    "capacity",
    "phi",
    "design strength",
    "available strength",
    "nominal strength",
    "compressive strength",
    "flexural strength",
    " pn",
    "net area",
    "kl/r",
    "slenderness",
    "buckl",
    "factored",
    "adequate",
    "moment capacity",
    "loads",
    "required",
    "re:\\bmu\\b|Mu"
   ],
   "go": "1 Lookup",
   "note": "Type the shape exactly as printed. If the tool says it is not a real shape, that is the trap: it lists the real ones."
  },
  {
   "id": "combo",
   "use": "problem",
   "continue": true,
   "question": "Are there WIND, SNOW, ROOF LIVE, RAIN or EARTHQUAKE loads? Or does the question ask only for the governing COMBINATION (no member size, capacity or moment)?",
   "signals": [
    "re:\\bwind\\b|wind",
    "re:\\bsnow\\b|snow",
    "roof live",
    "re:\\brain\\b|rain",
    "earthquake",
    "seismic",
    "load combination",
    "re:\\bp[ws]\\s*=|PW = , PS = (a load named W or S)"
   ],
   "unless": [],
   "go": "2 Loads > Load combinations FIRST",
   "note": "It prints the governing load. If the QUESTION asks only for that load or combination, you are done. If it asks anything about a member (select, capacity, check, slenderness ...), do this FIRST, then carry on down this ladder, type that load into the member form and tick 'already factored'.",
   "alone": [
    "combination",
    "uplift",
    "governing factored",
    "governing load",
    "controlling combination"
   ]
  },
  {
   "id": "floor",
   "use": "problem",
   "question": "Is there a FLOOR? Either the words 'floor plan' or 'framing plan', or loads in psf together with beams, girders, a slab or floors.",
   "strong": [
    "floor plan",
    "framing plan",
    "floor framing",
    "floor system"
   ],
   "all": [
    "re:\\bpsf\\b|lb/ft\\^?2|per square foot|per sq|psf, lb/ft^2"
   ],
   "signals": [
    "beam",
    "girder",
    "joist",
    "slab",
    "floor"
   ],
   "unless": [],
   "go": "6 Floor plan (or 2 Loads > Column takedown for a column under several floors)",
   "note": "Loads per square foot (psf) on a floor are the giveaway. Bolt spacing 'on center' is NOT a floor.",
   "unless_anywhere": [
    "tension rod",
    "hung from",
    "suspended from",
    "hanger rod"
   ]
  },
  {
   "id": "tension",
   "use": "question_then_problem",
   "question": "Is the member PULLED? Bolt holes are the usual giveaway. (Bolts, holes and welds with no other member word also mean Tension.)",
   "signals": [
    "tension",
    "tensile",
    "hanger",
    "net area",
    "a net",
    "anet",
    "shear lag",
    "rupture",
    "bolt hole",
    "holes in",
    "hole in",
    "staggered",
    "gage",
    "gusset",
    "tie rod",
    "tension rod",
    "in tension",
    "pulled",
    "threaded rod",
    "eyebar"
   ],
   "unless": [],
   "go": "3 Tension",
   "note": "",
   "weak": [
    "bolt",
    "holes",
    "weld",
    "connected leg",
    "splice",
    "lines of",
    "yielding"
   ]
  },
  {
   "id": "column",
   "use": "question_then_problem",
   "question": "Is the member PUSHED end to end? (Beam words -- phi Mn, flexural, compression flange, Lb -- mean it is a beam, not a column.)",
   "signals": [
    "column",
    "axial compression",
    "compression member",
    "compression load",
    "compressive",
    "compr.",
    "buckling",
    "euler",
    "slenderness",
    "kl/r",
    "phi c",
    "pinned top",
    "pin ends",
    "pinned at",
    "pinned-pinned",
    "fixed at the base",
    "fixed at the bottom",
    "fixed-fixed",
    "unbraced length",
    "weak axis",
    "flagpole",
    "strut",
    "effective length",
    "re:\\bkl\\b|KL",
    "re:\\blc\\b|Lc",
    "cover plate",
    "fixed both",
    "pinned both",
    "pinned ends",
    "pin-ended",
    "pin ended",
    "hinged",
    "in compression",
    "compression strength",
    "compressive strength",
    "re:\\bkl[xy]\\b|KLx, KLy",
    "post",
    "pier",
    "stud column",
    "k factor",
    "re:\\bk\\s*=\\s*[0-2]|K = 0.8 (a given K)",
    "re:\\bpe\\b|Pe"
   ],
   "unless": [
    "phi mn",
    "phi mp",
    "phi b",
    "flexural",
    "compression flange",
    "re:\\blu?b\\s*=|Lb =",
    "table 3-10",
    "table 3-2",
    " cb ",
    "used as a beam",
    "design moment",
    "moment capacity",
    "moment strength",
    "beam with an unbraced",
    "beam has an unbraced",
    "unbraced length of the beam"
   ],
   "go": "4 Column",
   "note": "",
   "unless_anywhere": [
    "compression flange is unbraced",
    "compression flange unbraced",
    "unbraced compression flange",
    "re:\\blub\\b|Lub",
    "table 3-10",
    "re:\\blb\\s*=\\s*[1-9]|Lb = (not zero)"
   ]
  },
  {
   "id": "beam",
   "use": "question_then_problem",
   "question": "Is the member BENT by loads along its length?",
   "signals": [
    "beam",
    "girder",
    "moment",
    "flexural",
    "phi mn",
    "phi b",
    "re:\\bmu\\b|Mu",
    "simply supported",
    "simple span",
    "uniform load",
    "uniformly distributed",
    "k/ft",
    "kip/ft",
    "kips/ft",
    "lb/ft",
    "midspan",
    "mid-span",
    "cantilever",
    "zx",
    "laterally braced",
    "lateral support",
    "laterally supported",
    "reaction",
    "flexure",
    "bending",
    "phi mp",
    "klf",
    "plf",
    "lintel",
    "purlin",
    "header",
    "rafter",
    "compact"
   ],
   "unless": [],
   "go": "5 Beam",
   "note": "If the BEAM has an unbraced length (Lb, Lp, Lr, Cb), that is final-exam material: the tool does not do it.",
   "weak": [
    " span"
   ]
  },
  {
   "id": "loads",
   "use": "problem",
   "question": "Only loads to add up or factor, no member?",
   "signals": [
    "factored",
    "ultimate",
    "dead",
    "live",
    "service",
    "1.2d",
    "1.4d",
    " pu",
    "design load"
   ],
   "unless": [],
   "go": "2 Loads",
   "note": "",
   "last": true
  }
 ],
 "forms": {
  "words": [
   {
    "id": "W-def",
    "want": "A definition, a reason, a list",
    "signals": [],
    "tab": "Definitions"
   }
  ],
  "lookup": [
   {
    "id": "K-light",
    "want": "The lightest shape that has at least some property",
    "signals": [
     "lightest",
     "at least",
     "minimum of",
     ">=",
     "with a plastic",
     "with zx",
     "with ix",
     "with sx"
    ],
    "tab": "1 Lookup > Lightest with ..."
   },
   {
    "id": "K-mat",
    "want": "Fy or Fu of a steel",
    "signals": [
     "fy and fu",
     "fy of",
     "fu of",
     "what grade",
     "which steel",
     "steel grade",
     "minimum yield",
     "re:(yield|tensile) (stress|strength) of (a ?\\d|astm|grade|steel)|yield / tensile strength of A36, A992 ...",
     "fy for",
     "fu for",
     "yield strength for",
     "yield stress for",
     "tensile strength for",
     "minimum tensile",
     "specified minimum",
     "strength is specified"
    ],
    "tab": "1 Lookup > Fy and Fu"
   },
   {
    "id": "K-sect",
    "want": "Properties of a bar, a plate, or a W with cover plates (A, I, r)",
    "signals": [
     "section properties",
     "cover plate",
     "built-up",
     "built up",
     "round bar",
     "rectangular bar",
     "solid bar",
     "flat bar",
     "boxed",
     "re:\\bpl ?\\d|PL 1 x 12 (a plate)"
    ],
    "tab": "1 Lookup > Section properties"
   },
   {
    "id": "K-prop",
    "want": "A property of a named shape (depth, thickness, area, S, Z, I, r)",
    "signals": [
     "depth",
     "width",
     "thickness",
     "area",
     "modulus",
     "gyration",
     "inertia",
     "weight",
     "with units",
     "re:\\b(a|d|bf|tw|tf|ix|iy|sx|sy|zx|zy|rx|ry|rz|tdes|tnom) of |rx of a ..., tw of an ..."
    ],
    "tab": "1 Lookup > Shape property"
   },
   {
    "id": "K-prop2",
    "want": "Any other property of a named shape",
    "signals": [],
    "tab": "1 Lookup > Shape property"
   }
  ],
  "combo": [
   {
    "id": "L-comb",
    "want": "The governing factored load from several load types",
    "signals": [],
    "tab": "2 Loads > Load combinations"
   }
  ],
  "floor": [
   {
    "id": "F-take-sel",
    "want": "The SIZE of a column under several floors",
    "signals_all": [
     "column",
     "re:\\b(select|lightest|smallest|size|choose|design)\\b|select / size / lightest"
    ],
    "signals": [
     "stories",
     "story",
     "floors",
     "floor levels",
     "levels",
     "roof",
     "floor level",
     "each floor",
     "each level",
     "storey",
     "per floor"
    ],
    "unless": [
     "beam",
     "girder"
    ],
    "tab": "2 Loads > Column takedown",
    "then": "4 Column > Select a column"
   },
   {
    "id": "F-take",
    "want": "ONLY the load on a column under several floors (no beam or girder asked)",
    "signals_all": [
     "column"
    ],
    "signals": [
     "stories",
     "story",
     "floors",
     "floor levels",
     "levels",
     "roof",
     "floor level",
     "each floor",
     "each level",
     "storey",
     "per floor"
    ],
    "tab": "2 Loads > Column takedown",
    "unless": [
     "beam",
     "girder"
    ]
   },
   {
    "id": "F-maxl",
    "want": "The largest live load the floor beam can take",
    "signals": [
     "largest live",
     "maximum live",
     "max live",
     "maximum service live",
     "largest service live",
     "how much live",
     "greatest live",
     "allowable live",
     "largest uniform live",
     "largest superimposed",
     "maximum superimposed",
     "live load can",
     "what live load",
     "what uniform live",
     "safe live",
     "uniform live load in psf that"
    ],
    "tab": "5 Beam > Largest live load"
   },
   {
    "id": "F-plan",
    "want": "Loads on the beam, beam size, reaction, girder size (the usual chain)",
    "signals": [
     "beam",
     "girder",
     "slab",
     "floor",
     "tributary",
     "reaction"
    ],
    "tab": "6 Floor plan"
   },
   {
    "id": "F-plan2",
    "want": "Anything else on a floor",
    "signals": [],
    "tab": "6 Floor plan"
   }
  ],
  "tension": [
   {
    "id": "T-hole",
    "want": "Only the hole size",
    "q_only": true,
    "signals": [
     "hole diameter",
     "diameter of the hole",
     "hole size",
     "size of the hole",
     "size of hole",
     "standard hole",
     "effective hole",
     "diameter hole",
     "what hole",
     "hole should",
     "hole to use",
     "select the hole"
    ],
    "unless": [
     "capacity",
     "strength",
     "lightest",
     "adequate",
     "phi",
     "net width",
     "path",
     "hole diameter of",
     "hole diameter =",
     "hole diameter is",
     "using a hole",
     "with a hole",
     "holes of",
     "hole size of"
    ],
    "tab": "1 Lookup > Hole size"
   },
   {
    "id": "T-u",
    "want": "Only the shear lag factor U",
    "signals": [
     "shear lag factor",
     "what is u",
     "value of u",
     "determine u",
     "factor u",
     "which u",
     "u applies",
     "correct u"
    ],
    "unless": [
     "capacity",
     "strength",
     "phi",
     "lightest",
     "adequate",
     " pn",
     "how much",
     "carry",
     "net area",
     "u of 0",
     "u is 0",
     "re:\\bu\\s*=\\s*[01]\\b|U = 0.85 (a given value)"
    ],
    "tab": "1 Lookup > U (shear lag)"
   },
   {
    "id": "T-sel",
    "want": "Pick the lightest member",
    "signals": [
     "select",
     "lightest",
     "choose",
     "most economical",
     "design a ",
     "smallest w",
     "smallest shape",
     "smallest section",
     "smallest size",
     "smallest member",
     "smallest column",
     "smallest beam",
     "smallest angle",
     "smallest channel",
     "smallest standard",
     "smallest hss",
     "smallest tee",
     "what size",
     "size the",
     "size a ",
     "what shape",
     "which shape",
     "re:which w ?\\d|which W14 ...",
     "least weight",
     "minimum weight",
     "shape is required",
     "size is required",
     "shape should be used",
     "most efficient"
    ],
    "tab": "3 Tension > Select a member",
    "unless": [
     "hole size",
     "hole diameter",
     "size of the hole",
     "shear lag",
     "factor u",
     "select u",
     "value of u"
    ]
   },
   {
    "id": "T-req",
    "want": "The area the load needs",
    "signals": [
     "required area",
     "area required",
     "area is required",
     "minimum gross area",
     "required gross",
     "required net",
     "required ag",
     "required ae",
     "what gross area",
     "what net area",
     "what area",
     "required rod area",
     "rod area",
     "area needed",
     "area does"
    ],
    "tab": "3 Tension > Required area"
   },
   {
    "id": "T-pu",
    "want": "ONLY the factored load Pu",
    "q_only": true,
    "signals": [
     "find the factored",
     "determine the factored",
     "calculate the factored",
     "compute the factored",
     "what is the factored",
     "factored load pu",
     "find pu",
     "determine pu",
     "calculate pu",
     "compute pu",
     "what is pu",
     "what load do you design for",
     "required strength",
     "required axial strength",
     "required tensile strength",
     "required compressive strength",
     "required axial"
    ],
    "unless": [
     "design strength",
     "available strength",
     "nominal strength",
     "capacity",
     "phi pn",
     "select",
     "lightest",
     "adequate",
     "moment",
     "reaction",
     "area",
     "smallest w",
     "smallest shape",
     "smallest section",
     "smallest size",
     "smallest member",
     "smallest column",
     "smallest beam",
     "smallest angle",
     "smallest channel",
     "smallest standard",
     "smallest hss",
     "smallest tee",
     "size"
    ],
    "tab": "2 Loads > Factored load"
   },
   {
    "id": "T-maxl",
    "want": "The largest LIVE load it can carry",
    "signals": [
     "largest live",
     "maximum live",
     "max live",
     "maximum service live",
     "largest service live",
     "how much live",
     "greatest live",
     "allowable live",
     "largest uniform live",
     "largest superimposed",
     "maximum superimposed",
     "live load can",
     "what live load",
     "what uniform live",
     "safe live",
     "uniform live load in psf that"
    ],
    "tab": "3 Tension > Capacity",
    "then": "2 Loads > Max live load"
   },
   {
    "id": "T-cap",
    "want": "How much it can carry, the effective net area, or whether it is adequate",
    "signals": [
     "capacity",
     "strength",
     "phi pn",
     "pr =",
     "maximum load",
     "largest",
     "how much load",
     "can carry",
     "adequate",
     "first failure",
     "effective net area",
     " ae",
     "limit state",
     "yielding",
     "satisfactory",
     " pn",
     "phi t",
     "strong enough",
     "can resist",
     "can support",
     "check the",
     "is the plate",
     "does it work",
     "ok"
    ],
    "tab": "3 Tension > Capacity"
   },
   {
    "id": "T-net",
    "want": "Only the net area (holes taken out), or which path governs",
    "signals": [
     "net area",
     "minimum area",
     "a net",
     "anet",
     " an ",
     "net width",
     "rupture path",
     "failure path",
     "path governs",
     "each path",
     "possible paths",
     "staggered",
     "zigzag",
     "zig-zag"
    ],
    "tab": "3 Tension > Net area"
   },
   {
    "id": "T-cap2",
    "want": "Anything else about a tension member",
    "signals": [],
    "tab": "3 Tension > Capacity"
   }
  ],
  "column": [
   {
    "id": "C-eul",
    "want": "The Euler (critical buckling) load",
    "signals": [
     "euler",
     "critical buckling",
     "pcr",
     "critical load",
     "proportional limit",
     "euler load",
     "elastic buckling",
     "re:\\bpe\\s*=|Pe =",
     "re:critical stress[^;]{0,120}\\be\\s*=|critical stress with E given",
     "buckling load",
     "re:\\bpe\\b|Pe",
     "re:\\be\\s*=\\s*29|E = 29,000"
    ],
    "tab": "4 Column > Euler"
   },
   {
    "id": "C-sel",
    "want": "Pick the lightest column",
    "signals": [
     "select",
     "lightest",
     "choose",
     "most economical",
     "design a ",
     "design the ",
     "smallest w",
     "smallest shape",
     "smallest section",
     "smallest size",
     "smallest member",
     "smallest column",
     "smallest beam",
     "smallest angle",
     "smallest channel",
     "smallest standard",
     "smallest hss",
     "smallest tee",
     "what size",
     "size the",
     "size a ",
     "what shape",
     "which shape",
     "re:which w ?\\d|which W14 ...",
     "least weight",
     "minimum weight",
     "shape is required",
     "size is required",
     "shape should be used",
     "most efficient"
    ],
    "tab": "4 Column > Select a column",
    "unless": [
     "effective length factor",
     "k factor",
     "factor k",
     "select k",
     "choose k",
     "value of k",
     "appropriate k",
     "correct k"
    ]
   },
   {
    "id": "C-pu",
    "want": "ONLY the factored load Pu",
    "q_only": true,
    "signals": [
     "find the factored",
     "determine the factored",
     "calculate the factored",
     "compute the factored",
     "what is the factored",
     "factored load pu",
     "find pu",
     "determine pu",
     "calculate pu",
     "compute pu",
     "what is pu",
     "what load do you design for",
     "required strength",
     "required axial strength",
     "required tensile strength",
     "required compressive strength",
     "required axial"
    ],
    "unless": [
     "design strength",
     "available strength",
     "nominal strength",
     "capacity",
     "phi pn",
     "select",
     "lightest",
     "adequate",
     "moment",
     "reaction",
     "area",
     "smallest w",
     "smallest shape",
     "smallest section",
     "smallest size",
     "smallest member",
     "smallest column",
     "smallest beam",
     "smallest angle",
     "smallest channel",
     "smallest standard",
     "smallest hss",
     "smallest tee",
     "size"
    ],
    "tab": "2 Loads > Factored load"
   },
   {
    "id": "C-fcr",
    "want": "Only phi Fcr for a given KL/r",
    "q_only": true,
    "signals": [
     "critical stress",
     "phi fcr",
     "fcr",
     "design stress",
     "table 4-14",
     "stress for kl/r",
     "stress at kl/r"
    ],
    "unless": [
     "capacity",
     "strength",
     "phi pn",
     "select",
     "lightest",
     "adequate",
     "which axis"
    ],
    "tab": "1 Lookup > phi Fcr from KL/r"
   },
   {
    "id": "C-maxl",
    "want": "The largest LIVE load it can carry",
    "signals": [
     "largest live",
     "maximum live",
     "max live",
     "maximum service live",
     "largest service live",
     "how much live",
     "greatest live",
     "allowable live",
     "largest uniform live",
     "largest superimposed",
     "maximum superimposed",
     "live load can",
     "what live load",
     "what uniform live",
     "safe live",
     "uniform live load in psf that"
    ],
    "tab": "4 Column > Capacity of a column",
    "then": "2 Loads > Max live load"
   },
   {
    "id": "C-cap",
    "want": "Capacity, KL/r, which axis governs, or whether it is adequate",
    "signals": [
     "capacity",
     "strength",
     "phi pn",
     "phi c",
     "adequate",
     "satisfactory",
     "kl/r",
     "slenderness",
     "governs",
     "can carry",
     "can it carry",
     "maximum load",
     "largest load",
     "how much load",
     "allowable",
     " pn",
     "strong enough",
     "check the",
     "ok",
     "does it work",
     "can support",
     "resist",
     "is the column",
     "available strength"
    ],
    "tab": "4 Column > Capacity of a column"
   },
   {
    "id": "C-k",
    "want": "Only the effective length factor K (or KL)",
    "q_only": true,
    "signals": [
     "effective length factor",
     "value of k",
     "what is k",
     "effective length",
     " k for ",
     " k of ",
     "factor k",
     "k factor",
     "which k",
     "what k",
     "k applies",
     "k value",
     "select k",
     "choose k"
    ],
    "unless": [
     "capacity",
     "strength",
     "kl/r",
     "slenderness",
     "lightest",
     "adequate",
     " pn",
     "euler",
     "k = 0",
     "k = 1",
     "k = 2",
     "k of 0",
     "k of 1",
     "k of 2"
    ],
    "tab": "1 Lookup > K"
   },
   {
    "id": "C-cap2",
    "want": "Anything else about a column",
    "signals": [],
    "tab": "4 Column > Capacity of a column"
   }
  ],
  "beam": [
   {
    "id": "B-sel",
    "want": "Pick the most economical beam",
    "signals": [
     "select",
     "lightest",
     "most economical",
     "choose",
     "economy",
     "size the",
     "design a ",
     "design the ",
     "smallest w",
     "smallest shape",
     "smallest section",
     "smallest size",
     "smallest member",
     "smallest column",
     "smallest beam",
     "smallest angle",
     "smallest channel",
     "smallest standard",
     "smallest hss",
     "smallest tee",
     "what size",
     "size a ",
     "what shape",
     "which shape",
     "re:which w ?\\d|which W14 ...",
     "least weight",
     "minimum weight",
     "shape is required",
     "size is required",
     "shape should be used",
     "most efficient"
    ],
    "tab": "5 Beam > Select a beam"
   },
   {
    "id": "B-maxl",
    "want": "The largest load the beam can take",
    "signals": [
     "largest live",
     "maximum live",
     "max live",
     "maximum service live",
     "largest service live",
     "how much live",
     "greatest live",
     "allowable live",
     "largest uniform live",
     "largest superimposed",
     "maximum superimposed",
     "live load can",
     "what live load",
     "what uniform live",
     "safe live",
     "uniform live load in psf that",
     "maximum uniform",
     "largest uniform",
     "largest load",
     "how much load",
     "safe load"
    ],
    "tab": "5 Beam > Largest live load"
   },
   {
    "id": "B-pu",
    "want": "ONLY the factored line load wu",
    "q_only": true,
    "signals": [
     "factored uniform load",
     "factored load wu",
     "find wu",
     "determine wu",
     "what is wu",
     "factored line load",
     "factored distributed load"
    ],
    "unless": [
     "moment",
     "reaction",
     "shear",
     "select",
     "lightest",
     "capacity",
     "adequate",
     "re:\\bmu\\b|Mu",
     "size"
    ],
    "tab": "2 Loads > Factored load"
   },
   {
    "id": "B-dem",
    "want": "The moment the loads DEMAND (the required strength Mu)",
    "q_only": true,
    "signals": [
     "required flexural strength",
     "required moment",
     "required strength",
     "required mu",
     "required bending"
    ],
    "unless": [
     "adequate",
     "capacity",
     "phi mn",
     "can ",
     "satisf",
     "select",
     "lightest",
     "smallest w",
     "smallest shape",
     "smallest section",
     "smallest size",
     "smallest member",
     "smallest column",
     "smallest beam",
     "smallest angle",
     "smallest channel",
     "smallest standard",
     "smallest hss",
     "smallest tee",
     "size"
    ],
    "tab": "5 Beam > Moment and reactions"
   },
   {
    "id": "B-cap",
    "want": "The design moment of a named beam, or whether it is adequate",
    "signals": [
     "design moment capacity",
     "phi mn",
     "phi mp",
     "phi b",
     "moment capacity",
     "flexural strength",
     "design flexural",
     "capacity of",
     "adequate",
     "can be used",
     "can it be used",
     "flexural design strength",
     "design strength",
     "moment strength",
     "nominal moment",
     "plastic moment",
     "satisfactory",
     " mn ",
     " mp ",
     "can resist",
     "can carry",
     "can support",
     "carry the loads",
     "resist",
     "strong enough",
     "ok for",
     "ok in",
     "check the beam",
     "check the w",
     "check whether",
     "check if",
     "largest factored moment",
     "moment can",
     "does it work",
     "is the beam",
     "re:design moment (of|capacity|strength)|design moment of a W..",
     "its design moment",
     "flexural capacity",
     "bending capacity",
     "bending strength",
     "moment resistance"
    ],
    "tab": "5 Beam > Capacity of a beam"
   },
   {
    "id": "B-zx",
    "want": "The Zx the load needs",
    "signals": [
     "required zx",
     "zx required",
     "required plastic"
    ],
    "tab": "5 Beam > Required Zx"
   },
   {
    "id": "B-mom",
    "want": "Maximum moment, reactions, shear",
    "signals": [
     "moment",
     "reaction",
     "shear",
     "re:\\b(mu|vu|ru|ra|rb|wu)\\b|Mu, Vu, RA, RB, wu",
     "factored load",
     "diagram"
    ],
    "tab": "5 Beam > Moment and reactions"
   },
   {
    "id": "B-mom2",
    "want": "Anything else about a beam",
    "signals": [],
    "tab": "5 Beam > Moment and reactions"
   }
  ],
  "loads": [
   {
    "id": "L-take-sel",
    "want": "The SIZE of a column under several floors",
    "signals_all": [
     "column",
     "re:\\b(select|lightest|smallest|size|choose|design)\\b|select / size / lightest"
    ],
    "signals": [
     "stories",
     "story",
     "floors",
     "levels",
     "roof",
     "floor level",
     "each floor",
     "each level",
     "storey",
     "per floor"
    ],
    "tab": "2 Loads > Column takedown",
    "then": "4 Column > Select a column"
   },
   {
    "id": "L-take",
    "want": "The load on a column under several floors",
    "signals": [
     "stories",
     "story",
     "floors",
     "levels",
     "roof",
     "floor level",
     "each floor",
     "each level",
     "storey",
     "per floor"
    ],
    "tab": "2 Loads > Column takedown"
   },
   {
    "id": "L-max",
    "want": "The largest live load for a known capacity",
    "signals": [
     "largest live",
     "maximum live",
     "max live",
     "maximum service live",
     "largest service live",
     "how much live",
     "greatest live",
     "allowable live",
     "largest uniform live",
     "largest superimposed",
     "maximum superimposed",
     "live load can",
     "what live load",
     "what uniform live",
     "safe live",
     "uniform live load in psf that"
    ],
    "tab": "2 Loads > Max live load"
   },
   {
    "id": "L-fact",
    "want": "A factored load from dead and live",
    "signals": [
     "factored",
     "ultimate",
     "1.2d",
     "1.4d",
     " pu",
     "design load",
     "design for"
    ],
    "tab": "2 Loads > Factored load"
   },
   {
    "id": "L-fact2",
    "want": "Anything else that is only loads",
    "signals": [],
    "tab": "2 Loads > Factored load"
   }
  ],
  "convert": [
   {
    "id": "K-unit",
    "want": "A unit conversion",
    "signals": [],
    "tab": "1 Lookup > Units"
   }
  ]
 },
 "grab": {
  "tension_capacity": [
   [
    "Shape",
    "the member's name: W14x90, WT6x20, C10x20, L4x4x1/2. A plate: its width and thickness"
   ],
   [
    "Bolt diameter",
    "'7/8-in diameter bolts'. Type 7/8. The tool adds the 1/8 for the hole"
   ],
   [
    "Holes per flange",
    "'two holes in each flange' -> 2"
   ],
   [
    "Holes in the web",
    "'three holes in its web' -> 3"
   ],
   [
    "Fasteners per line",
    "'4 holes in each line', 'four bolts in a row' -> 4"
   ],
   [
    "Connected through",
    "flanges AND web -> all parts; only flanges; only web; an angle -> one leg"
   ],
   [
    "Welded",
    "'welded', 'no bolt holes' -> tick it and leave the hole boxes empty"
   ],
   [
    "Loads",
    "only when it asks 'adequate?': service loads in D and L; a 'factored' or 'Pu' load -> tick already factored"
   ]
  ],
  "tension_net_area": [
   [
    "Plate width and thickness",
    "add up the figure's dimensions; if the text and the figure disagree, the FIGURE wins"
   ],
   [
    "Bolt diameter",
    "as printed, e.g. 1/2"
   ],
   [
    "Each hole",
    "across = how far it is from one edge of the plate; along = how far it is shifted in the direction of the pull (0 for holes in the same row)"
   ]
  ],
  "tension_select": [
   [
    "Family",
    "'lightest W8', '10 in deep channel' = C10, 'WT6', 'L4'"
   ],
   [
    "Loads",
    "PD and PL in D and L; 'factored' / 'Pu' -> tick already factored"
   ],
   [
    "Welded or bolted",
    "welded -> tick it; bolted -> bolt diameter, holes, where it is connected, bolts per line"
   ],
   [
    "Length",
    "only if it gives one (for the L/r check)"
   ]
  ],
  "lookup_U": [
   [
    "Where it is connected",
    "web only, flanges only, all parts, or an angle's one leg"
   ],
   [
    "Fasteners per line",
    "'4 holes in each line' -> 4"
   ],
   [
    "Shape",
    "needed for the flange case (the tool compares bf with 2/3 d)"
   ]
  ],
  "column_capacity": [
   [
    "Shape",
    "the column's name"
   ],
   [
    "Length",
    "the full height in ft"
   ],
   [
    "End conditions",
    "'pinned top and bottom', 'fixed at the base and pinned at the top', 'fixed both ends', 'free at the top' (flagpole), 'free to sway'"
   ],
   [
    "Braces",
    "'braced at mid-height about the weak axis' -> weak-axis length = half; braces at given heights -> the segment lengths. Braces shorten ONLY the weak axis unless it says both"
   ],
   [
    "Load",
    "only when it asks 'adequate?'"
   ]
  ],
  "column_select": [
   [
    "Family",
    "'lightest W10', or several: W10, W12, W14"
   ],
   [
    "Loads",
    "PD and PL, or the factored load with the box ticked"
   ],
   [
    "Length and end conditions",
    "same as for a capacity"
   ]
  ],
  "column_euler": [
   [
    "Section",
    "a shape name, or a bar: round diameter, or width and thickness"
   ],
   [
    "Length and end conditions",
    "as printed"
   ],
   [
    "Proportional limit",
    "type it if the problem gives one (it decides whether Euler applies)"
   ]
  ],
  "beam_analysis": [
   [
    "Span",
    "in ft (inches / 12)"
   ],
   [
    "Uniform loads",
    "dead and live in k/ft (lb/ft / 1000)"
   ],
   [
    "Point loads",
    "each one: where it is and its dead and live parts, or its factored value"
   ],
   [
    "Own weight",
    "'includes the beam weight' -> nothing to add; otherwise the self-weight box"
   ],
   [
    "Cantilever",
    "choose cantilever and say whether distances are from the WALL or the FREE END"
   ]
  ],
  "beam_select": [
   [
    "The moment or the loads",
    "Mu directly, or span and loads"
   ],
   [
    "Depth limit",
    "'W16 only', 'depth limited to', 'flat ceiling', 'same depth as' -> allowed depths"
   ]
  ],
  "beam_capacity": [
   [
    "Shape",
    "the beam's name"
   ],
   [
    "Mu",
    "only when it asks 'adequate?'"
   ]
  ],
  "beam_max_live_load": [
   [
    "Shape, span, spacing",
    "as printed"
   ],
   [
    "Dead loads",
    "slab thickness, other dead load in psf"
   ]
  ],
  "floor_plan": [
   [
    "Slab or dead load",
    "slab thickness in inches, OR the dead load in psf if it is given directly"
   ],
   [
    "Other dead load",
    "ceiling, mechanical, flooring, FIXED partitions (psf)"
   ],
   [
    "Steel framing",
    "'steel framing = 6 psf' -> the framing box; then no self-weight recheck"
   ],
   [
    "Live load",
    "psf. A second live load (MOVABLE partitions) goes in the second box: she takes the LARGER"
   ],
   [
    "Beam",
    "span, spacing, interior or edge"
   ],
   [
    "Girder",
    "span, where the beams land on it, beams on one side or both"
   ]
  ],
  "loads_combinations": [
   [
    "Each load",
    "D, L, Lr (roof live), S (snow), R (rain), W (wind), E (earthquake)"
   ],
   [
    "Reversing wind or earthquake",
    "a second, opposite value goes in the REVERSE box as a positive number"
   ]
  ],
  "loads_takedown": [
   [
    "Tributary area",
    "square feet, or the two bay dimensions"
   ],
   [
    "Roof",
    "dead and live in psf (leave empty if there is no roof)"
   ],
   [
    "Floors",
    "dead and live in psf, and how many floors"
   ]
  ],
  "loads_factored": [
   [
    "D and L",
    "service dead and live"
   ]
  ],
  "lookup_shape": [
   [
    "Shape",
    "exactly as printed"
   ],
   [
    "Property",
    "depth d, web thickness tw, flange width bf, area A, Sx, Zx, Ix, Iy, rx, ry"
   ]
  ],
  "lookup_definition": [
   [
    "Search words",
    "the two or three key words of the question"
   ]
  ],
  "lookup_hole": [
   [
    "Bolt diameter",
    "as printed, e.g. 7/8. The tool adds the 1/8"
   ]
  ],
  "lookup_K": [
   [
    "End conditions",
    "top and bottom: pinned, fixed, free, free to sway"
   ]
  ],
  "lookup_critical_stress": [
   [
    "KL/r",
    "the slenderness ratio (the tool rounds it UP, as she does)"
   ],
   [
    "Fy",
    "50 unless the problem says otherwise"
   ]
  ],
  "lookup_by_property": [
   [
    "Property and minimum",
    "e.g. Ix at least 500 in^4"
   ],
   [
    "Family",
    "W, or a nominal depth such as W16"
   ]
  ],
  "lookup_material": [
   [
    "Shape or grade",
    "W14x90, an HSS, A36, A992 ..."
   ]
  ],
  "tension_required_area": [
   [
    "Loads",
    "PD and PL, or the factored load with the box ticked"
   ],
   [
    "Steel",
    "Fy and Fu, only if it is not the default for the shape"
   ]
  ],
  "beam_required_zx": [
   [
    "Mu",
    "the factored moment in kip-ft"
   ],
   [
    "Fy",
    "50 unless the problem says otherwise"
   ]
  ],
  "loads_max_service": [
   [
    "phi Rn",
    "the capacity, from the Capacity form"
   ],
   [
    "Dead load",
    "the service dead load D"
   ]
  ],
  "units": [
   [
    "The number and its unit",
    "as printed"
   ],
   [
    "The unit wanted",
    "ft, in, k/ft, kip-ft ..."
   ],
   [
    "Width",
    "only for psf to k/ft: the tributary width in ft"
   ]
  ],
  "section_properties": [
   [
    "Shape",
    "the W, if there is one"
   ],
   [
    "Plates or bar",
    "plate thickness and width; or a bar's diameter, or width and thickness"
   ],
   [
    "Where the plates go",
    "on the flange faces (cover plates) or at the flange tips (boxed)"
   ]
  ]
 },
 "traps": [
  {
   "id": "factored",
   "when": "a factored / ultimate load is GIVEN (Pu, Mu, wu)",
   "do": "Is the load given as factored or ultimate? Then tick 'already factored' and do not use the D and L boxes. (If it gives dead and live loads and ASKS for the factored load, do not tick it.)",
   "signals": [
    "factored load of",
    "factored axial load of",
    "factored moment of",
    "ultimate load of",
    "ultimate axial load of",
    "ultimate moment of",
    "an ultimate",
    "a factored",
    "re:\\b[pmw]u\\s*=\\s*\\d|Pu = , Mu = , wu = (with a number)"
   ]
  },
  {
   "id": "service",
   "when": "service / dead / live loads (PD, PL)",
   "do": "Service loads go in the D and L boxes. The tool factors them (the larger of 1.2D + 1.6L and 1.4D).",
   "signals": [
    "service",
    "dead load",
    "live load",
    " dead",
    " live",
    "re:\\bp\\s?[dl]\\s*=|PD = , PL ="
   ]
  },
  {
   "id": "dead-only",
   "when": "only a dead load, no live load",
   "do": "1.4D governs. Type D and leave L empty: the tool does it and says so.",
   "signals": [
    "dead"
   ],
   "unless": [
    "live",
    "re:\\bp\\s?l\\s*=|PL =",
    "snow",
    "wind",
    "roof",
    "rain",
    "earthquake",
    "seismic",
    "imposed",
    "occupancy",
    "re:\\b(l|lr|s|w|e)\\s*=|L = , S = , W ="
   ]
  },
  {
   "id": "welded",
   "when": "welded / no bolt holes",
   "do": "Tick 'welded'. Only yielding is checked (no holes, no U).",
   "signals": [
    "welded",
    "weld ",
    "welds",
    "no bolt holes",
    "no holes"
   ],
   "families": [
    "tension"
   ]
  },
  {
   "id": "per-line",
   "when": "holes in each line / bolts in a row / bolts per line",
   "do": "This is NOT the number of holes across the section. It goes in 'fasteners per line' (it sets U).",
   "signals": [
    "in each line",
    "per line",
    "in the line",
    "in a line",
    "in one line",
    "bolts in line"
   ],
   "unless": [
    "across"
   ]
  },
  {
   "id": "holes-across",
   "when": "holes in each flange / holes in the web / lines of bolts",
   "do": "These are the holes ACROSS the section. They go in the hole boxes (holes per flange, web holes).",
   "signals": [
    "in each flange",
    "in the web",
    "in its web",
    "lines of",
    "rows of bolts",
    "gage line"
   ]
  },
  {
   "id": "figure",
   "when": "a figure, a sketch, 'as shown'",
   "do": "Read the dimensions off the FIGURE. If the figure and the text disagree, the figure wins (Quiz 1 Q7: text 7 in, figure 9 in).",
   "signals": [
    "shown",
    "figure",
    "sketch",
    "see below",
    "diagram"
   ]
  },
  {
   "id": "fake-shape",
   "when": "the tool says 'not a real shape'",
   "do": "That is the trap (Quiz 1: M8x3.7). Use the real shape it offers and write that you did.",
   "signals": [],
   "families": [
    "lookup"
   ]
  },
  {
   "id": "two-live",
   "when": "two live loads / movable partitions",
   "do": "She takes the LARGER of the two, not the sum. Put the second one in the second live-load box.",
   "signals": [
    "partition",
    "movable",
    "moveable",
    "two live"
   ]
  },
  {
   "id": "framing",
   "when": "steel framing given in psf / the dead load includes the beam's weight",
   "do": "Do not add the beam's own weight again (use the framing box, or tick 'includes self-weight').",
   "signals": [
    "steel framing",
    "includes the beam",
    "includes its own weight",
    "including its own weight",
    "includes the weight",
    "including the weight",
    "own weight",
    "self-weight",
    "self weight"
   ]
  },
  {
   "id": "depth",
   "when": "W16 only / depth limited / flat ceiling / same depth",
   "do": "Fill 'allowed depths'. The lightest shape overall is then the wrong answer.",
   "signals": [
    "re:\\bw\\s?\\d+ only|W16 only",
    "depth limited",
    "limited to",
    "flat ceiling",
    "same depth",
    "same nominal depth",
    "nominal depth",
    "not deeper",
    "no deeper",
    "maximum depth",
    "clearance",
    "headroom"
   ]
  },
  {
   "id": "weak-brace",
   "when": "braced about the weak axis / a brace at mid-height / perpendicular to the weak axis",
   "do": "Only the WEAK-axis length gets shorter (use the brace boxes). The strong axis keeps the full height unless the problem says both.",
   "signals": [
    "weak axis",
    "weak (y",
    "y-y",
    "mid-height",
    "midheight",
    "mid height",
    "third points",
    "third-points",
    "braced at",
    "brace at",
    "bracing",
    "lateral brace",
    "horizontal brace"
   ],
   "families": [
    "column"
   ]
  },
  {
   "id": "k",
   "when": "fixed / pinned / free ends",
   "do": "Choose the end condition and the tool fills K. She uses the DESIGN values: fixed-fixed 0.65, fixed-pinned 0.8, pinned-pinned 1.0, fixed with sway 1.2, flagpole 2.1, pinned with sway 2.0.",
   "signals": [
    "fixed",
    "pinned",
    "pin ",
    "pins",
    "hinged",
    "free at",
    "sway",
    "flagpole",
    "sidesway"
   ],
   "families": [
    "column"
   ]
  },
  {
   "id": "units",
   "when": "inches, lb/ft, kip-in",
   "do": "The forms want ft, k/ft and kip-ft, as plain numbers (18 ft 6 in = 18.5). 1 Lookup > Units converts.",
   "signals": [
    "lb/ft",
    "plf",
    "lb per",
    "pounds",
    "kip-in",
    "k-in",
    "in-kip",
    "inches long",
    "in. long",
    "in long",
    "re:\\d+\\s*(ft|')\\s*-?\\s*\\d+\\s*(in|\")|18 ft 6 in"
   ]
  },
  {
   "id": "cantilever",
   "when": "a cantilever (fixed at one end, free at the other)",
   "do": "Choose support = cantilever, and 'positions FROM THE FREE END' if that is how the problem measures.",
   "signals": [
    "cantilever",
    "free end",
    "fixed end"
   ]
  },
  {
   "id": "other-beams",
   "when": "an overhanging, continuous or fixed-ended beam",
   "do": "NOT in the tool (it does simple spans and cantilevers). Get the moment by statics, then use 5 Beam > Select a beam with that Mu.",
   "signals": [
    "overhang",
    "continuous beam",
    "fixed at both ends",
    "fixed-fixed beam",
    "fixed-end beam",
    "propped"
   ],
   "not_in_tool": true,
   "families": [
    "beam",
    "floor"
   ]
  },
  {
   "id": "comp-flange",
   "when": "compression flange fully braced / Lb = 0 / full lateral support",
   "do": "'Compression flange braced' / 'Lb = 0' describes a BEAM with full support. If the member is bent by loads along its length, use 5 Beam, not 4 Column.",
   "signals": [
    "compression flange",
    "lb = 0",
    "lb=0",
    "full lateral support",
    "continuously braced",
    "laterally supported",
    "braced by the slab"
   ],
   "unless": [
    "unbraced",
    "not braced"
   ],
   "families": [
    "column"
   ]
  },
  {
   "id": "final-beam",
   "when": "a BEAM whose compression flange is NOT fully braced (unbraced length, Lb, Lp, Lr, Cb, Table 3-10)",
   "do": "Final-exam material. NOT in the tool: it only does fully braced beams (Lb = 0).",
   "signals": [
    "re:\\blu?b\\s*=\\s*[1-9][0-9.]*\\s*(ft|feet|')|Lb = (not zero) ft",
    "re:\\blub\\b|Lub",
    "re:\\bl b\\s*=\\s*[1-9]|L_b = (not zero)",
    "re:\\blu?b (equals|of|is) [1-9]|Lb equals ...",
    "table 3-10",
    " cb ",
    "re:\\blp\\s*=|Lp =",
    "re:\\blr\\s*=\\s*[0-9.]+\\s*(ft|feet)|Lr = ... ft",
    "compression flange is unbraced",
    "compression flange unbraced",
    "unbraced compression flange",
    "laterally unbraced",
    "lateral-torsional",
    "lateral torsional",
    "lp and lr",
    "re:\\blp\\b|Lp"
   ],
   "not_in_tool": true,
   "unless": []
  },
  {
   "id": "final-beam2",
   "when": "a BEAM with lateral bracing only at certain points (unbraced length)",
   "do": "Final-exam material. NOT in the tool: it only does fully braced beams (Lb = 0).",
   "signals": [
    "unbraced",
    "lateral support only at",
    "braced only at",
    "lateral bracing at",
    "lateral support at",
    "bracing is at",
    "bracing only at",
    "braced at the supports",
    "braced at the ends",
    "braces at",
    "braced every",
    "braced at mid",
    "braced at the third",
    "braced at third",
    "no intermediate brac",
    "no lateral",
    "without lateral",
    "not laterally",
    "bracing is provided at",
    "brace points",
    "no intermediate",
    "not braced",
    "braced against lateral",
    "no continuous brac",
    "at its ends and at",
    "braced at its ends",
    "between its supports",
    "supports are provided only",
    "only at the beam ends",
    "only at the ends",
    "only at its ends",
    "provided only at",
    "bracing at the ends"
   ],
   "unless": [
    "lb = 0",
    "lb=0",
    "fully braced",
    "full lateral",
    "continuously braced",
    "continuous lateral",
    "braced by the slab",
    "braced continuously",
    "continuously"
   ],
   "families": [
    "beam",
    "floor"
   ],
   "not_in_tool": true
  },
  {
   "id": "final-only",
   "when": "shear STRENGTH / deflection / block shear / bolt or weld STRENGTH / combined axial load and bending / composite beams",
   "do": "Final-exam material. NOT in the tool. Write what you can and move on.",
   "signals": [
    "shear strength",
    "phi vn",
    "check shear",
    "shear check",
    "shear capacity",
    "adequate in shear",
    "shear and deflection",
    "block shear",
    "bolt shear",
    "shear plane",
    "web yielding",
    "web crippling",
    "deflection",
    "re:\\bl/(360|240|180)\\b|L/360",
    "sag",
    "number of bolts required",
    "bolts are required",
    "bolt strength",
    "bearing strength",
    "bearing-type",
    "bearing type",
    "bolt bearing",
    "bearing at",
    "threads excluded",
    "threads included",
    "slip-critical",
    "slip critical",
    "weld length",
    "length of weld",
    "weld size",
    "size of the weld",
    "size of weld",
    "weld strength",
    "interaction",
    "combined axial",
    "axial load and bending",
    "axial compression and bending",
    "axial tension and bending",
    "bending and axial",
    "beam-column",
    "eccentric",
    "re:axial (load|force|compression|tension)[^.]{0,40}\\band\\b[^.]{0,20}\\bmoment\\b|axial load and a moment",
    "composite",
    "shear stud",
    "headed stud",
    "shored",
    "consider shear",
    "check for shear",
    "based on shear",
    "governed by shear",
    "adequate for shear",
    "re:(strength|capacity|size|length) of (a |an |the )?[^;]{0,30}\\bwelds?\\b|strength of a weld",
    "re:\\bwelds?\\b[^;.]{0,40}\\b(strength|capacity)\\b|weld ... strength",
    "strength of the connection",
    "capacity of the connection",
    "connection can carry",
    "connection can transfer",
    "load the connection",
    "lapped",
    "lap joint",
    "smaw",
    "shear and moment only",
    "consider shear and",
    "re:how many [^.;?]{0,30}bolts|how many ... bolts",
    "single shear",
    "double shear",
    "bolts are needed",
    "bolts needed",
    "effective width of the slab",
    "effective slab width",
    "act as one unit",
    "shear connector"
   ],
   "not_in_tool": true,
   "unless": [
    "re:(neglect|ignore|disregard|need not|do not need|no need|not need|don't need|do not check|don't check|not be checked|not required|not to be checked|without checking)[^.;]{0,60}(shear|deflection|bearing|weld|bolt)|neglect / no need to check ... shear, deflection"
   ]
  },
  {
   "id": "tee-column",
   "when": "a tee (WT), a double angle (2L) or a single angle used as a COLUMN",
   "do": "The tool prints NOT RELIABLE for these shapes in compression. Use the Manual's table for that shape.",
   "signals": [
    "re:\\b(wt|2l)\\s?\\d|WT.. or 2L..",
    "double angle",
    "single angle",
    "re:\\bl\\s?\\d+\\s?x|L4x4.."
   ],
   "families": [
    "column"
   ]
  },
  {
   "id": "two-angles",
   "when": "a double angle / 2L / two angles back to back in tension",
   "do": "The tension forms have an 'angles' box: 2 = double angle.",
   "signals": [
    "double angle",
    "two angles",
    "2l",
    "back to back",
    "back-to-back"
   ],
   "families": [
    "tension"
   ]
  },
  {
   "id": "stagger",
   "when": "staggered / zigzag holes",
   "do": "Plates: 3 Tension > Net area, type each hole's position and the tool tries every path. Staggered holes in a W or an angle are NOT in the tool.",
   "signals": [
    "staggered",
    "stagger",
    "zigzag",
    "zig-zag"
   ]
  },
  {
   "id": "ties",
   "when": "two shapes of the same weight both work",
   "do": "The tool applies her Table 3-2 rule and says which one it took and why. Write the one it prints.",
   "signals": []
  }
 ],
 "keywords": [
  [
   "actual depth, web width, flange width",
   "a property of a shape",
   "1 Lookup > Shape property"
  ],
  [
   "adequate, is it OK, can it carry, check",
   "capacity compared with the load",
   "the Capacity form of that member, with the load typed"
  ],
  [
   "Anet, net area, minimum area",
   "area with the holes taken out",
   "3 Tension > Net area"
  ],
  [
   "Ae, effective net area",
   "U times the net area",
   "3 Tension > Capacity (read Ae in the key numbers)"
  ],
  [
   "axial compression, compressive load",
   "a column",
   "4 Column"
  ],
  [
   "bay, tributary, psf, slab",
   "floor framing",
   "6 Floor plan"
  ],
  [
   "beam, girder, span, moment",
   "a bent member",
   "5 Beam"
  ],
  [
   "braced at mid-height, third points",
   "the weak axis has shorter lengths",
   "4 Column, the brace boxes"
  ],
  [
   "cantilever, fixed at one end, free end",
   "a beam held at one end",
   "5 Beam > Moment and reactions, support = cantilever"
  ],
  [
   "capacity, design strength, phi Pn, PR",
   "how much the member can carry",
   "the Capacity form of that member"
  ],
  [
   "column, strut, flagpole",
   "a pushed member",
   "4 Column"
  ],
  [
   "cover plates, reinforced with plates, built-up",
   "a section made of parts",
   "4 Column > Capacity of a column (plate boxes), or 1 Lookup > Section properties"
  ],
  [
   "critical buckling load, Euler, Pcr",
   "elastic buckling",
   "4 Column > Euler"
  ],
  [
   "define, is called, which of the following, explain, why",
   "a word question",
   "Definitions"
  ],
  [
   "economy table, most economical",
   "lightest beam for a moment",
   "5 Beam > Select a beam"
  ],
  [
   "effective length factor, K",
   "depends on the end conditions",
   "1 Lookup > K"
  ],
  [
   "factored, ultimate, Pu, Mu",
   "already multiplied by the load factors",
   "tick 'already factored'"
  ],
  [
   "floor plan, framing plan",
   "the floor chain",
   "6 Floor plan"
  ],
  [
   "gage, pitch, staggered, zigzag",
   "holes not in one row",
   "3 Tension > Net area (hole positions)"
  ],
  [
   "hanger, tie, tension, tensile",
   "a pulled member",
   "3 Tension"
  ],
  [
   "KL/r, slenderness ratio",
   "length over radius of gyration",
   "4 Column > Capacity of a column (key numbers)"
  ],
  [
   "largest live load, maximum live load",
   "work backwards from the capacity",
   "5 Beam > Largest live load, or 2 Loads > Max live load"
  ],
  [
   "lightest, select, choose, design a",
   "pick a size",
   "the Select form of that member"
  ],
  [
   "load combinations, wind, snow, earthquake, roof live, rain",
   "several load types",
   "2 Loads > Load combinations"
  ],
  [
   "maximum moment, Mu, reactions",
   "beam statics",
   "5 Beam > Moment and reactions"
  ],
  [
   "phi Fcr, critical stress at KL/r",
   "one number from Table 4-14",
   "1 Lookup > phi Fcr from KL/r"
  ],
  [
   "phi Mn, phi Mp, design moment, flexural strength",
   "beam capacity",
   "5 Beam > Capacity of a beam"
  ],
  [
   "pinned, fixed, free, sway",
   "end conditions (they set K)",
   "the end-condition boxes of 4 Column"
  ],
  [
   "proportional limit",
   "the test for whether Euler applies",
   "4 Column > Euler"
  ],
  [
   "radius of gyration, moment of inertia, section modulus",
   "properties of a shape",
   "1 Lookup > Shape property"
  ],
  [
   "shear lag factor, U",
   "the reduction for a partial connection",
   "1 Lookup > U (shear lag)"
  ],
  [
   "stories, floors, roof, tributary area (for a column)",
   "loads added down a building",
   "2 Loads > Column takedown"
  ],
  [
   "uniform load, k/ft, lb/ft",
   "a load along a beam",
   "5 Beam"
  ],
  [
   "welded, no bolt holes",
   "no holes: yielding only",
   "tick 'welded'"
  ],
  [
   "yield strength, modulus of elasticity, ductility",
   "material words",
   "Definitions"
  ]
 ],
 "version": "3.8",
 "tabs": {
  "1 Lookup > Shape property": [
   "lookup",
   "lookup_shape"
  ],
  "1 Lookup > Lightest with ...": [
   "lookup",
   "lookup_by_property"
  ],
  "1 Lookup > Fy and Fu": [
   "lookup",
   "lookup_material"
  ],
  "1 Lookup > Section properties": [
   "lookup",
   "section_properties"
  ],
  "1 Lookup > U (shear lag)": [
   "lookup",
   "lookup_U"
  ],
  "1 Lookup > K": [
   "lookup",
   "lookup_K"
  ],
  "1 Lookup > phi Fcr from KL/r": [
   "lookup",
   "lookup_critical_stress"
  ],
  "1 Lookup > Hole size": [
   "lookup",
   "lookup_hole"
  ],
  "1 Lookup > Units": [
   "lookup",
   "units"
  ],
  "2 Loads > Factored load": [
   "loads",
   "loads_factored"
  ],
  "2 Loads > Floor load": [
   "loads",
   "loads_floor"
  ],
  "2 Loads > Column takedown": [
   "loads",
   "loads_takedown"
  ],
  "2 Loads > Load combinations": [
   "loads",
   "loads_combinations"
  ],
  "2 Loads > Max live load": [
   "loads",
   "loads_max_service"
  ],
  "3 Tension > Net area": [
   "tension",
   "tension_net_area"
  ],
  "3 Tension > Capacity": [
   "tension",
   "tension_capacity"
  ],
  "3 Tension > Select a member": [
   "tension",
   "tension_select"
  ],
  "3 Tension > Required area": [
   "tension",
   "tension_required_area"
  ],
  "4 Column > Euler": [
   "column",
   "column_euler"
  ],
  "4 Column > Capacity of a column": [
   "column",
   "column_capacity"
  ],
  "4 Column > Select a column": [
   "column",
   "column_select"
  ],
  "5 Beam > Moment and reactions": [
   "beam",
   "beam_analysis"
  ],
  "5 Beam > Capacity of a beam": [
   "beam",
   "beam_capacity"
  ],
  "5 Beam > Select a beam": [
   "beam",
   "beam_select"
  ],
  "5 Beam > Required Zx": [
   "beam",
   "beam_required_zx"
  ],
  "5 Beam > Largest live load": [
   "beam",
   "beam_max_live_load"
  ],
  "6 Floor plan": [
   "floor",
   "floor_plan"
  ],
  "Definitions": [
   "defs",
   "lookup_definition"
  ],
  "Her rules": [
   "rules",
   null
  ],
  "Known gaps": [
   "gaps",
   null
  ]
 },
 "load_ask_words": [
  "combination",
  "governing factored",
  "governing load",
  "controlling combination",
  "controlling load",
  "factored load",
  "factored axial",
  "ultimate load",
  "design load",
  "uplift",
  "maximum factored",
  "largest factored",
  "re:\\b(pu|wu)\\b|Pu, wu"
 ]
};
})(typeof globalThis !== 'undefined' ? globalThis : (typeof window !== 'undefined' ? window : this));

